version: '{build}'
branches:
  only:
  - master
  - /^v\d+(?:\.\d+)?$/
  - /[\b_]validate\b/
skip_tags: true
skip_commits:
  files:
    - doc/*
    - .github/*
    - '**/*.md'
    - .vsts-ci.yml
nuget:
  disable_publish_on_pr: true
image: Visual Studio 2017
configuration: Release
environment:
  VisualStudioVersion: 15.0
  TreatWarningsAsErrors: true
  CodeAnalysisTreatWarningsAsErrors: true
before_build:
  msbuild src\GuidGen.sln /nologo /m /v:quiet /t:restore
build:
  verbosity: minimal
test_script:
- cmd: >-
    SET testdir=bin\GuidGenTests\%configuration%\

    "%userprofile%\.nuget\packages\OpenCover\4.6.519\tools\OpenCover.Console.exe"
    -register:user
    -target:"%xunit20%\xunit.console.x86.exe"
    -targetargs:"%testdir%GuidGenTests.dll -noshadow -html %testdir%testresults.html -xml %testdir%testresults.xml -appveyor -notrait TestCategory=FailsInCloudTest -nologo"
    -returntargetcode
    -excludebyattribute:*.ExcludeFromCodeCoverage*
    -excludebyfile:*\*Designer.cs
    -filter:"+[GuidGen]*"
    -hideskipped:All
    -output:%testdir%code_coverage.xml

    SET PATH=C:\Python34;C:\Python34\Scripts;%PATH%

    pip install codecov

    codecov -f "%testdir%code_coverage.xml"
artifacts:
- path: bin\GuidGenVsPackage\%configuration%\GuidGenVsPackage.vsix
  name: VS Package
- path: bin\GuidGen\%configuration%\GuidGen.exe
  name: WPF Application
