trigger:
  batch: true
  branches:
    include:
    - main
    - 'validate/*'
  paths:
    exclude:
    - doc/
    - '*.md'
    - .vscode/
    - .github/
    - azure-pipelines/release.yml

parameters:
- name: RunTests
  displayName: Run tests
  type: boolean
  default: true

variables:
- template: /azure-pipelines/BuildStageVariables.yml@self

jobs:
- template: azure-pipelines/build.yml
  parameters:
    Is1ESPT: false
    EnableMacOSBuild: false
    EnableLinuxBuild: false
    RunTests: ${{ parameters.RunTests }}
